### ISSUE TITLE
📖 Seastar Documentation

### ISSUE THREAD

**Issue by nithinmanoj10** [bfGraph/STGraph#25]
Structure and content for Seastar API Documentation

**Comment by JoelMathewC** [comment]
To finalize on the design for Seastar we will need the following diagrams

- [ ] Activity Diagram
- [ ] Class Diagram

**Comment by JoelMathewC** [comment]
# Landing Page

## Seastar Documentation and Tutorial

Seastar is a cutting-edge system designed to enhance the performance of graph neural network (GNN) and Temporal-GNN training on GPUs. Utilize the vertex-centric approach to programming a GNN to produce highly efficient fused GPU kernels for forward and backward passes. It achieves better usability, faster computation time and consumes less memory than state-of-the-art GNN systems like DGL and PyG.

Dive into this documentation to learn more and try out writing your own GNN and T-GNN models after following our beginner-friendly tutorial
